dist: xenial
language: python
python:
  - 3.6
  - 3.7

notifications:
  email:
    - nick.hand@phila.gov

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.conda

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test

  # install dependencies
  - conda install -c conda-forge --yes --file requirements.txt

  # install package itself
  - pip install .[dev]

script:
  - py.test . --cov carto2gpd

after_success:
  - coveralls
