package:
  name: carto2gpd
  version: {{ environ.get("TRAVIS_TAG", "")  }}

source:
  git_url: https://github.com/PhiladelphiaController/carto2gpd.git
  git_rev: {{ environ.get("TRAVIS_TAG", "")  }}

build:
  script_env: 
    - TRAVIS_TAG
  number : 0
  script : python setup.py install
  
requirements:
  host:
    - python
    - setuptools
    - geopandas

  run:
    - python
    - requests
    - geopandas

test:
  imports:
    - carto2gpd

