{% set name = "carto2gpd" %}
{% set version = environ.get("LATEST_VERSION", "") %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/PhiladelphiaController/carto2gpd.git
  git_rev: {{ version }}

build:
  script_env: 
    - LATEST_VERSION
  number: 0
  script : pip install .

requirements:
  host:
    - python
    - requests
    - geopandas
    - poetry

  run:
    - python
    - requests
    - geopandas

test:
  imports:
    - carto2gpd

about:
  home: https://github.com/PhiladelphiaController/carto2gpd
  license: MIT
  license_family: MIT
  summary: A Python utility to query a CARTO database and return a geopandas GeoDataFrame

extra:
  recipe-maintainers:
    - PhiladelphiaController
